//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.16 at 04:52:56 PM PST 
//


package com.mitchell.claims.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for LossInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LossInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CauseOfLoss" type="{http://www.mitchell.com/examples/claim}CauseOfLossCode" minOccurs="0"/&gt;
 *         &lt;element name="ReportedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="LossDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LossInfoType", propOrder = {
    "causeOfLoss",
    "reportedDate",
    "lossDescription"
})
@Embeddable
public class LossInfoType {

    @XmlElement(name = "CauseOfLoss")
    @XmlSchemaType(name = "string")
   @Column(name = "CauseOfLoss")
   @Enumerated(EnumType.STRING)
    protected CauseOfLossCode causeOfLoss;
    
    @XmlElement(name = "ReportedDate")
    @XmlSchemaType(name = "dateTime")
    @Transient
    protected XMLGregorianCalendar reportedDate;
    
    @XmlTransient
    @Column(name = "ReportedDate")
    @Temporal(TemporalType.TIMESTAMP)
    protected Date reportedDateDate;
    
    @XmlElement(name = "LossDescription")
    @Column(name = "LossDescription")
    protected String lossDescription;

    /**
     * Gets the value of the causeOfLoss property.
     * 
     * @return
     *     possible object is
     *     {@link CauseOfLossCode }
     *     
     */
    public CauseOfLossCode getCauseOfLoss() {
        return causeOfLoss;
    }

    /**
     * Sets the value of the causeOfLoss property.
     * 
     * @param value
     *     allowed object is
     *     {@link CauseOfLossCode }
     *     
     */
    public void setCauseOfLoss(CauseOfLossCode value) {
        this.causeOfLoss = value;
    }

    /**
     * Gets the value of the reportedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportedDate() {
        return reportedDate;
    }

    /**
     * Sets the value of the reportedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportedDate(XMLGregorianCalendar value) {
        this.reportedDate = value;
    }

    /**
     * Gets the value of the lossDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLossDescription() {
        return lossDescription;
    }

    /**
     * Sets the value of the lossDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLossDescription(String value) {
        this.lossDescription = value;
    }

	public Date getReportedDateDate() {
		return reportedDateDate;
	}

	public void setReportedDateDate(Date reportedDateDate) {
		this.reportedDateDate = reportedDateDate;
	}

    
}
